# Generated by Django 3.1.1 on 2020-12-22 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appuser', '0005_auto_20201221_2117'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, null=True)),
                ('shop_address', models.CharField(max_length=500, null=True)),
                ('shop_image', models.ImageField(blank=True, null=True, upload_to='shops')),
                ('shop_contact', models.CharField(max_length=10, null=True)),
                ('shop_address_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appuser.area')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
