# Generated by Django 3.1.1 on 2020-12-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201222_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_close_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_open_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_days',
            field=models.ManyToManyField(to='product.Week'),
        ),
    ]
