# Generated by Django 3.1.1 on 2020-12-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_confirmedorder_ordered_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedorder',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
