# Generated by Django 3.1.1 on 2020-12-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20201225_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmedorder',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordered_product',
            name='shop',
            field=models.CharField(max_length=100),
        ),
    ]
