# Generated by Django 3.1.1 on 2020-12-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_auto_20201221_2056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='States',
            new_name='State',
        ),
    ]
