# Generated by Django 3.1.1 on 2020-12-21 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0004_auto_20201221_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='area_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appuser.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='city_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appuser.state'),
        ),
    ]
