# Generated by Django 3.1.1 on 2020-12-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0005_auto_20201221_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownuser',
            name='is_shop_owner',
            field=models.BooleanField(default=False),
        ),
    ]
